### ISSUE TITLE
Missing @ReadOnly in the Hospital Course Instrument

### ISSUE THREAD

**Issue by overdonecashew89** [RollieParrish/COVID-QIR#43]
Hospital Course @Readonly text is missing in all of the auto-populated fields in the Hospital Course Instrument of the Redcap template.

**Comment by overdonecashew89** [comment]
It appears that that @Readonly tag is also missing in demographics and covidtesting

**Comment by RollieParrish** [comment]
Thanks - this is corrected in the COVID-QIR template project
